#!/bin/sh
set -eu

: "${PORT:=80}"
: "${AUTH_SERVICE_HOST:=auth-service:8001}"
: "${RIDER_SERVICE_HOST:=rider-service:8002}"
: "${FLEET_SERVICE_HOST:=fleet-service:8003}"
: "${FLEET_TELEMETRY_HOST:=fleet-telemetry:8013}"
: "${PAYMENTS_SERVICE_HOST:=payments-service:8004}"
: "${MARKETPLACE_SERVICE_HOST:=marketplace-service:8005}"
: "${MAINTENANCE_SERVICE_HOST:=maintenance-service:8006}"
: "${SKILLS_SERVICE_HOST:=skills-service:8007}"
: "${SUPPORT_SERVICE_HOST:=support-service:8008}"

: "${AUTH_SERVICE_URL:=http://${AUTH_SERVICE_HOST}}"
: "${RIDER_SERVICE_URL:=http://${RIDER_SERVICE_HOST}}"
: "${FLEET_SERVICE_URL:=http://${FLEET_SERVICE_HOST}}"
: "${FLEET_TELEMETRY_URL:=http://${FLEET_TELEMETRY_HOST}}"
: "${PAYMENTS_SERVICE_URL:=http://${PAYMENTS_SERVICE_HOST}}"
: "${MARKETPLACE_SERVICE_URL:=http://${MARKETPLACE_SERVICE_HOST}}"
: "${MAINTENANCE_SERVICE_URL:=http://${MAINTENANCE_SERVICE_HOST}}"
: "${SKILLS_SERVICE_URL:=http://${SKILLS_SERVICE_HOST}}"
: "${SUPPORT_SERVICE_URL:=http://${SUPPORT_SERVICE_HOST}}"

export PORT
export AUTH_SERVICE_HOST
export RIDER_SERVICE_HOST
export FLEET_SERVICE_HOST
export FLEET_TELEMETRY_HOST
export PAYMENTS_SERVICE_HOST
export MARKETPLACE_SERVICE_HOST
export MAINTENANCE_SERVICE_HOST
export SKILLS_SERVICE_HOST
export SUPPORT_SERVICE_HOST
export AUTH_SERVICE_URL
export RIDER_SERVICE_URL
export FLEET_SERVICE_URL
export FLEET_TELEMETRY_URL
export PAYMENTS_SERVICE_URL
export MARKETPLACE_SERVICE_URL
export MAINTENANCE_SERVICE_URL
export SKILLS_SERVICE_URL
export SUPPORT_SERVICE_URL

envsubst '${PORT} ${AUTH_SERVICE_HOST} ${RIDER_SERVICE_HOST} ${FLEET_SERVICE_HOST} ${FLEET_TELEMETRY_HOST} ${PAYMENTS_SERVICE_HOST} ${MARKETPLACE_SERVICE_HOST} ${MAINTENANCE_SERVICE_HOST} ${SKILLS_SERVICE_HOST} ${SUPPORT_SERVICE_HOST} ${AUTH_SERVICE_URL} ${RIDER_SERVICE_URL} ${FLEET_SERVICE_URL} ${FLEET_TELEMETRY_URL} ${PAYMENTS_SERVICE_URL} ${MARKETPLACE_SERVICE_URL} ${MAINTENANCE_SERVICE_URL} ${SKILLS_SERVICE_URL} ${SUPPORT_SERVICE_URL}' \
  < /etc/nginx/templates/nginx.conf.template \
  > /etc/nginx/nginx.conf
