apiVersion: v1
kind: Namespace
metadata:
  name: yana-staging
  labels:
    app.kubernetes.io/name: yana-os
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: yana-production
  labels:
    app.kubernetes.io/name: yana-os
    environment: production
