apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  namespace: yana-production
  labels:
    app.kubernetes.io/name: yana-os
    app.kubernetes.io/component: maintenance-service
spec:
  selector:
    app: maintenance-service
  ports:
    - name: http
      protocol: TCP
      port: 8006
      targetPort: 8006
  type: ClusterIP
